export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const hiddenPages = ["/Login", "/Register","/Aadhar","/Otp","/"];
  const pathname = usePathname(); 
  return (
    <html lang="en">
      <body>
        {children}
      </div>
        </body>
    </html>
  )
}
